package:
    name: AdcircPy
    version: 0.8.0
language: python
sudo: false
python:
  - "3.6"
install:
  - apt-get update
  # - pip install virtualenv
  - python -m virtualenv env
  - source ./env/bin/activate
  # - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - export PATH="$HOME/miniconda/bin:$PATH"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # - conda info -a
  # - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib pyproj netCDF4 scipy gdal wget
  # - source activate test-environment
  # - pip install haversine
  - python setup.py install

script:
  - mkdir ~/.cache/AdcircPy
  - touch ~/.cache/AdcircPy/h_tpxo9.v1.nc
  - python -c "import AdcircPy"

