name: AdcircPy
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - asn1crypto==0.24.0
  - bcrypt==3.1.4
  - beautifulsoup4==4.6.3
  - bs4==0.0.1
  - cffi==1.11.5
  - cftime==1.0.2.1
  - chardet==3.0.4
  - cryptography==2.3.1
  - cycler==0.10.0
  - dnspython==1.15.0
  - eventlet==0.24.1
  - greenlet==0.4.15
  - haversine==1.0.1
  - idna==2.7
  - kiwisolver==1.0.1
  - matplotlib==3.0.1
  - monotonic==1.5
  - netcdf4==1.4.2
  - numpy==1.15.3
  - paramiko==2.4.2
  - paramiko-expect==0.2.8
  - pkginfo==1.4.2
  - pyasn1==0.4.4
  - pycparser==2.19
  - pynacl==1.3.0
  - pyparsing==2.3.0
  - pyproj==1.9.5.1
  - python-dateutil==2.7.5
  - requests==2.20.0
  - requests-toolbelt==0.8.0
  - scipy==1.1.0
  - six==1.11.0
  - tqdm==4.26.0
  - twine==1.11.0
  - urllib3==1.24
  - utm==0.4.2
  - wget==3.2

