name: AdcircPy
channels:
- anaconda
- defaults
dependencies:
- blas
- bzip2
- ca-certificates
- cairo
- certifi
- cftime
- curl
- expat
- fontconfig
- freetype
- freexl
- gdal
- geos
- giflib
- glib
- hdf4
- hdf5
- icu
- intel-openmp
- jpeg
- json-c
- kealib
- krb5
- libboost
- libcurl
- libdap4
- libedit
- libffi
- libgcc-ng
- libgdal
- libgfortran-ng
- libkml
- libnetcdf
- libpng
- libpq
- libspatialite
- libssh2
- libstdcxx-ng
- libtiff
- libuuid
- libxcb
- libxml2
- mkl
- mkl_fft
- mkl_random
- ncurses
- netcdf4
- numpy
- numpy-base
- openjpeg
- openssl
- pcre
- pip
- pixman
- poppler
- poppler-data
- proj4
- pyproj
- python
- readline
- setuptools
- sqlite
- tk
- wheel
- xerces-c
- xz
- zlib
- pip:
  - cycler
  - cython
  - haversine
  - kiwisolver
  - matplotlib
  - mkl-fft
  - mkl-random
  - pyparsing
  - python-dateutil
  - pytz
  - scipy
  - six
  - wget

