name: AdcircPy
channels:
- anaconda
- defaults
dependencies:
- blas=1.0
- bzip2=1.0.6
- ca-certificates
- cairo=1.14.12
- cftime=1.0.0b1
- curl=7.61.0
- expat=2.2.6
- fontconfig=2.13.0
- freetype=2.9.1
- freexl=1.0.5
- gdal=2.3.0
- geos=3.6.2
- giflib=5.1.4
- glib=2.56.2
- hdf4=4.2.13
- hdf5=1.8.18
- icu=58.2
- intel-openmp=2018.0.3
- jpeg=9b
- json-c=0.13.1
- kealib=1.4.7
- krb5=1.16.1
- libboost=1.67.0
- libcurl=7.61.0
- libdap4=3.19.1
- libedit=3.1.20170329
- libffi=3.2.1
- libgcc-ng=8.2.0
- libgdal=2.3.0
- libgfortran-ng=7.3.0
- libkml=1.3.0
- libnetcdf=4.6.1
- libpng=1.6.34
- libpq=10.5
- libspatialite=4.3.0a
- libssh2=1.8.0
- libstdcxx-ng=8.2.0
- libtiff=4.0.9
- libuuid=1.0.3
- libxcb=1.13
- libxml2=2.9.8
- mkl=2018.0.3
- mkl_fft=1.0.4
- mkl_random=1.0.1
- ncurses=6.1
- netcdf4=1.4.1
- numpy=1.15.1
- numpy-base=1.15.1
- openjpeg=2.3.0
- openssl=1.0.2p
- pcre=8.42
- pixman=0.34.0
- poppler=0.65.0
- poppler-data=0.4.9
- proj4=5.0.1
- pyproj=1.9.5.1
- python=3.6.6
- readline=7.0
- sqlite=3.24.0
- tk=8.6.8
- xerces-c=3.2.10
- xz=5.2.4
- certifi=2016.2.28
- pip=9.0.1
- setuptools=36.4.0
- wheel=0.29.0
- zlib=1.2.11
- pip:
  - cycler==0.10.0
  - haversine==0.4.5
  - kiwisolver==1.0.1
  - matplotlib==2.2.3
  - mkl-fft==1.0.4
  - mkl-random==1.0.1
  - pyparsing==2.2.0
  - python-dateutil==2.7.3
  - pytz==2018.5
  - scipy==1.1.0
  - six==1.11.0
  - wget==3.2

