version: 2
jobs:
  build:
    docker:
        - image: jreniel/ci-adcircpy:alpine-conda 
    environment:
      BASH_ENV: "~/.bashrc"
    steps:
      - checkout
      # - run:
      #     name: "Updating conda"
      #     command: conda update -n base conda
      - run: cd .circleci/tests
      - run:
          name: "Install AdcircPy to local"
          command: python setup.py install
      - run: mkdir -p ~/.cache/AdcircPy
      - run: tar xf /tmp/test_data.tar.gz -C ~/.cache/AdcircPy h_tpxo9.v1.nc
      - run: tar xf /tmp/test_data.tar.gz -C ~/.cache CubaIkeModNOMAD1enoflux.grd 
      - run: tar xf /tmp/test_data.tar.gz -C ~/.cache fort13nomad1elowerwaterdrag
      - run: tar xf /tmp/test_data.tar.gz -C ~/.cache Sandy/control/coldstart/fort.15
      - run: ln -sf ~/.cache/CubaIkeModNOMAD1enoflux.grd fort.14
      - run: ln -sf ~/.cache/fort13nomad1elowerwaterdrag fort.13
      - run: ln -sf ~/.cache/Sandy/control/coldstart/fort.15 fort.15
      - run: python setup.py test
      # - run:
      #     name: "Basic import test"
      #     command: python -c "import AdcircPy"
      # - run:
      #     name: "Test Read Mesh"
      #     command: python ci-test-read_mesh.py


workflows:
  version: 2
  build:
    jobs:
      - build

