version: 2

jobs:

  build:
    docker:
        - image: jreniel/ci-adcircpy:alpine-conda
    
    environment:
      BASH_ENV: "~/.bashrc"
    
    steps:
      - checkout
      - run:
          name: "Updating conda"
          command: conda update -n base conda
      - run:
          name: "Install AdcircPy to local"
          command: python setup.py install
      - run: tar xf /tmp/test_data.tar.gz -C /root/.cache h_tpxo9.v1
      - run: tar xf /tmp/test_data.tar.gz -C /root/.cache CubaIkeModNOMAD1enoflux.grd
      - run: tar xf /tmp/test_data.tar.gz -C /root/.cache fort13nomad1elowerwaterdrag
      - run: tar xf /tmp/test_data.tar.gz -C /root/.cache fort.15
      - run: ln -sf /root/.cache/CubaIkeModNOMAD1enoflux.grd .circle-ci/tests/fort.14
      - run: ln -sf /root/.cache/fort13nomad1elowerwaterdrag .circle-ci/tests/fort.13
      - run: ln -sf /root/.cache/fort13nomad1elowerwaterdrag .circle-ci/tests/fort.15  
      - run:
          name: "Basic import test"
          command: python -c "import AdcircPy"
      - run:
          name: "Test Read Mesh"
          command: python .circle-ci/tests/ci-test-read_mesh.py

workflows:
  version: 0
  build_and_test:
    jobs:
      - build
