version: 2
jobs:
  build:
    docker:
        - image: jreniel/ci-adcircpy:Dockerfile
    environment:
      BASH_ENV: "~/.bashrc"
    steps:
      - checkout
      - run:
          name: "Updating conda"
          command: conda update -n base conda
      - run:
          name: "Install AdcircPy to local"
          command: python setup.py install
      - run: mkdir -p ~/.cache/AdcircPy
      - run: tar xf /tmp/test_data.tar.gz
      - run: mv h_tpxo9.v1.nc ~/.cache/AdcircPy/
      - run: python tests/ci-tests.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
