name: tests

on: [ push ]

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
          restore-keys : ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name : Install dependencies
        run : |
          apt-get update -y && apt-get install -y libnetcdf-dev libnetcdff-dev
          pip install wheel
          pip install -e .[development]
      - name : Test with coverage
        run : coverage run --source adcircpy -m nose --nologcapture --verbose
      - name : Generate coverage report
        run : coverage report -m
      - name : Upload coverage to Codecov
        uses : codecov/codecov-action@v1
        with :
          flags : unittests # optional
          fail_ci_if_error : true # optional (default = false)
          verbose : true # optional (default = false)

# https://stackoverflow.com/questions/59203704/how-create-a-badge-with-test-coverage-jacoco-on-github-actions
