name: tests

on: [push]

jobs:
  tests:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve packages from cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-conda-${{ hashFiles('setup.py') }}
      - name: Install dependencies
        run: pip install
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with coverage
        run: coverage run --source adcircpy -m nose --nologcapture --verbose
      - name: Generate coverage report
        run: coverage report -m